version: '3'

services:
  elasticsearch:
    container_name: "elasticsearch"
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    environment:
      - "node.name=es-server-7-01"
      - "bootstrap.memory_lock=true"
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es7-data:/usr/share/elasticsearch/data
  elasticsearch-hq:
    image: "elastichq/elasticsearch-hq:latest"
    container_name: "elasticsearch-hq"
    ports:
      - "5002:5000"
volumes:
  es7-data:
